---
language: python
services: docker

env:
  global:
    - ROLE_NAME: dsmrreader
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: fedora29

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible molecule yamllint ansible-lint docker
  - ansible-galaxy install --roles-path . geerlingguy.postgresql

  # Check ansible & molecule version
  - ansible --version
  #- molecule --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=/home/travis/.ansible/roles' >ansible.cfg
  - printf '[defaults]\nallow_world_readable_tmpfiles=True' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-galaxy install -r requirements.yml
  # - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/