# from galaxy
- src: geerlingguy.postgresql
  version: master

# # from GitHub, overriding the name and specifying a specific tag
# - src: https://github.com/kgizdov/ansible-role-postgresql/
#   version: chicken_or_egg_user_db
#   name: geerlingguy.postgresql_temp
