---
# handlers file for ansible-role-dsmrreader
- name: restart service postgresql
  service:
    name: postgresql
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: reloaded

- name: restart supervisord
  supervisorctl:
    name: "{{ item.group }}"
    state: restarted
  loop:
    - { group: dsmr_webinterface }
    - { group: dsmr_backend }
    - { group: dsmr_datalogger, restart: "{{ enable_datalogger }}" }
  when: item.restart | default(True) | bool