---
# handlers file for ansible-role-dsmrreader
- name: restart service postgresql
  service:
    name: postgresql
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: reloaded