---
- name: reread config
  supervisorctl:
    name: "{{ item.group }}"
    state: present
  loop:
    - { group: dsmr_webinterface }
    - { group: dsmr_backend }
    - { group: dsmr_datalogger, reread: "{{ enable_datalogger }}" }
  when: item.reread | default(True) | bool
- name: enable service supervisord and start it
  systemd:
    name: supervisor
    enabled: yes
    state: started
- name: update the supervisor running configuration
  supervisorctl:
    name: "{{ item.group }}"
    state: restarted
  loop:
    - { group: dsmr_webinterface }
    - { group: dsmr_backend }
    - { group: dsmr_datalogger, restart: "{{ enable_datalogger }}" }
  when: item.restart | default(True) | bool