---
- name: Converge
  hosts: all
  become: true
  vars:
    no_log: false
    postgresql_databases:
      - name: dsmrreader
    postgresql_users:
      - name: dsmrreader
      - password: dsmrreader
    ansible_ssh_pipelining: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

  tasks:
    - name: "Include ansible-role-dsmrreader"
      include_role:
        name: "ansible-role-dsmrreader"
